### ISSUE TITLE
Formatted hard drive and a lot of unspecified files after using CleanRip

### ISSUE THREAD

**Issue by 3rF1nd3rI5Ch3rF1nd3r** [emukidid/cleanrip#102]
I use CleanRip to digitize my GameCube game collection. Every time I use CleanRip with a GameCube disc, I end up with a formatted hard drive with many unspecified files (see screenshot). My existing database of WBFS titles is deleted, and the USB loader can no longer access any files. This makes CleanRip unusable for me. The hard drive is even renamed each time. Normally, the HDD is named "WII-USB".
![Screenshot 2024-07-14 120654](https://github.com/user-attachments/assets/7eae72e3-19cb-44ee-b78d-77a7665d02f8)

**Comment by 3rF1nd3rI5Ch3rF1nd3r** [comment]
It seems that it has something to do with the download of DAT files from redump.org. If I select "No" to downloading them, then this doesn't happen. But I want to ensure that the resulting dumps are clean and accurate. So, is there any fix?

**Comment by bibarub** [comment]
does this only happen when redownloading (updating) dat files? or does it happen on the first download as well?

**Comment by emukidid** [comment]
You've potentially fixed this @bibarub. @3rF1nd3rI5Ch3rF1nd3r try using the latest DOL from here: https://github.com/emukidid/cleanrip/actions/runs/12554183355/artifacts/2373046160

**Comment by 3rF1nd3rI5Ch3rF1nd3r** [comment]
> does this only happen when redownloading (updating) dat files? or does it happen on the first download as well?

It happens on the first download as well.
