### ISSUE TITLE
Crashes after asking about redump .dat files

### ISSUE THREAD

**Issue by Bujiraso** [emukidid/cleanrip#47]
Hi there,
I ran this on my Wii (Hombrew Channel latest 1.2, and System Version 4.2U) and I am encountering a crash after being asked about the .dat files. I've answered both yes and no and they both crash the application and system.

The following is the output:

```
Exception (DSI) occurred!
GPR00 FFFFFC70 GPR08 00000001 GPR16 801B36E8 GPR24 801C25FC
GPR01 8029C4F8 GPR09 00000078 GPR17 00000001 GPR25 FFFFFFFF
GPR02 801C23C8 GPR10 00000000 GPR18 801B3194 GPR26 00000000
GPR03 8027C080 GPR11 801C46F8 GPR19 801C4BFC GPR27 8050D4F0
GPR04 00000400 GPR12 84242042 GPR20 801B3600 GPR28 00000000
GPR05 00000000 GPR13 801C4BC0 GPR21 801B3168 GPR29 8027C080
GPR06 00000005 GPR14 801B3174 GPR22 801B35B0 GPR30 801C44B8
GPR07 00000048 GPR15 8020A600 GPR23 801B3584 GPR31 00000408
LR 80071174 SRR0 80071258 SRR1 0000b032 MSR 00001000
DAR 00000004 DSISR 04000000

STACK DUMP:
80071258 --> 80071174 --> 80043e08 --> 8003e068 -->
800385a0 --> 80023248 --> 80021fd8 --> 8000d16c -->
8006f170 

GODE DUMP:
80071258: 813C0004 5529003A 7C1F4850 2F80000F
80071268: 2F000000 419D01D4 409801D8 839C000C
80071278: 7F8BE000 409EFFDC 38E70001 839E0010
```

The attached device is a 64GB micro SD running through a Transcend USB-microSD converter. The 64GB has only an NTFS file-system containing nothing but the gc.dat at the root. There is no disc in the console. In the front SD port is a 1GB microSD in an SD converter which was used to run the program.

**Comment by Bujiraso** [comment]
Worked around by using the same microSD card in the front SD slot, formatted to FAT32.
The same gc.dat file was on the root.

This is possibly a USB or NTFS problem.

**Comment by Bujiraso** [comment]
A similar crash occurred when I later added the wii.dat file to the root of the same FAT32 drive.
Removing the file allowed the program to continue, however it complained on subsequent run that there were no .dat files found (when the gc.dat file was still there).

Notably, when the ripping began, it said at the bottom that "Gamecube Redump.org DAT in use". So one of these messages is showing in error.

**Comment by InternalLoss** [comment]
While this is somewhat moot right now as Redump does not have the DATs for public consumption and thus GC-Forever's is somewhat outdated, having this not crash the app would be a good idea as we could then establish some sort of server that can grab the latest dat file every ~7 days and then send it to the wii

**Comment by emukidid** [comment]
Fixed by 0a90b99b1e9d1f669934b67723f586af8e820494

**Comment by Spidy123222** [comment]
I seem to have the same problem and I just said no this time for dumping and it seems to work now so far.

**Comment by InternalLoss** [comment]
You're using the latest CleanRip, right?

**Comment by Spidy123222** [comment]
> You're using the latest CleanRip, right?

What it seems like it's the latest version.

**Comment by gabeklavans** [comment]
I appear to also be having this issue. I let CleanRip download the files it asked for, and the app worked fine. Next time I booted it up, it detected the files, I let it check for updates, and every time I do it crashes during the check. Skipping the check allows the app to work fine.

**Comment by RELOADthatREMIX** [comment]
I'm having the same issue at the moment on my vWii. I select my SD card as the "dump" location, select FAT, etc. and after I go through the update checks it crashes. Unsure if this is a problem with CleanRip on vWii or if it is a current problem on all version of Wiis. I do have an OG Wii but the disk drive is currently out of order, which is why I'm trying to backup my games to be able to play them on that Wii with USB Loader GX. This is also the plan for the vWIi.
