### ISSUE TITLE
Disk Image Corruption

### ISSUE THREAD

**Issue by melsbacksfriend** [emukidid/cleanrip#51]
I was dumping Super Smash Bros. Brawl and it didn't dump it properly because it had the file size of a single layer disc although it is dual layer so I used USB loader GX to dump it and it worked fine.  BTW I'm using the vwii of a modded wii u.

**Comment by fancymelonub** [comment]
How do you use Loader GX to dump discs?

**Comment by emukidid** [comment]
You need to tell CleanRip that it's a dual layer disc, I don't have a list of dual layer discs which is what I assume USBLoaderGX does when you're "installing" a disc.

**Comment by Bombastisch** [comment]
Well there theoretically is a list of dual-layer disc wii games:

https://wiki.dolphin-emu.org/index.php?title=Category:Dual_Layer_Disc_games

I don't have the programming skills to implement this tho.
