### ISSUE TITLE
Build dependencies?

### ISSUE THREAD

**Issue by DMSalesman** [emukidid/cleanrip#55]
I would like to build CleanRip with the latest commits, but `make` fails by complaining about `mxml.h` not existing, even after I installed `libmxml-dev`. `mxml.h` exists under `/usr/include/`. The host is a 32 bit machine running Debian 9.6.0.

Is it possible to add a build dependency list to the README?

**Comment by ac90b671** [comment]
Your `libmxml-dev` is from your linux package manager with libs for x86.


To build cleanrip you're going to need to install [devkitpro](https://devkitpro.org/wiki/Getting_Started) to set up a PowerPC Wii build environment. From there, using the `pacman` in devkitpro, install `ppc-portlibs` (`pacman -S ppc-portlibs`), which includes `ppc-mxml`. You're also going to need built `libntfs` libs. AFAIK, the best way is to get them from [here](https://wiibrew.org/wiki/Libntfs) and build them from source using your devkitpro build environment. With `mxml` and `libntfs` in your libs path for your devkitpro environment, you should be able to run `make` in your devkitpro environment to build `cleanrip`.

**Comment by Meganium97** [comment]
How do I build libntfs, since it uses BOOL calls that C doesn't support?
