### ISSUE TITLE
Current Redump DATs crash CleanRip at end of dump

### ISSUE THREAD

**Issue by InternalLoss** [emukidid/cleanrip#57]
As title says, a current set of DATs crashes the program (likely due to memory constraints?)

Wii DAT is at 1.2MB, and GCN is at 653KB, with these probably going to increase as the final Wii PAL games are dumped, etc.

[A link to Redump's DATs have been attached](https://www.mediafire.com/folder/e3cdxxoh8kwlk/) as multiple people have pointed out that, due to this being directly related to fixing the issue, this should be fine. Furthermore, the current GCN and Wii dat's on gc-forever are outdated (and actually the program crashes on attempt to update), so they could be replaced with these if/when a fix is completed.

**Comment by Bombastisch** [comment]
The datfiles ( http://www.gc-forever.com/datfile/ ) are actually quite new. Redump just updates them very frequently and the "wii.dat" has been discontinued, so there aren't any major updates.

The download fails, because of a  older assumption, that the files aren't bigger than 1MB. You can work around that by manually placing the files on the SD card until the bug is fixed.

**Comment by InternalLoss** [comment]
Yes, the download fails of the wii.dat because it got bigger then 1MB; I used the workaround and placed the wii.dat manually on the SD card. When ripping a Wii disc, CleanRip crashes at the end of the dump (probably because it wants to compare the MD5 hash with the wii.dat file) This is probably also due to the fact that the wii.dat is bigger then 1MB

**Comment by HTV04** [comment]
Planning to rip my Wii discs as backups soon. Has this bug been fixed? How can I work around it?

**Comment by InternalLoss** [comment]
it has not; you can dump without the DAT, however.

**Comment by ac90b671** [comment]
I'm looking into making a fix for this issue

**Comment by Bombastisch** [comment]
It's fixed. Maybe @emukidid can make a new release

**Comment by ac90b671** [comment]
What was the issue? I looked through the changes that got merged in today and nothing looked to me like it addressed the issue. Increasing the download buffer size to 3mb isn't going to fix the crash. I changed that locally before today's changes were merged in and was still getting the crash. I'll try with what was merged in today when I get home later today.

**Comment by Bombastisch** [comment]
Oh. If the download buffer wasn't the fix then it might still not be working.

**Comment by ac90b671** [comment]
Yeah, the buffer is just used for downloading the dat file off the internet as a temporary before it's written to disk. It was just making the download fail. The crash is with iterating the data from the dat file that was loaded off disk (that may have just been put there by the download).

**Comment by emukidid** [comment]
Fixed by 0a90b99b1e9d1f669934b67723f586af8e820494
