### ISSUE TITLE
Allow for repeated dumps with the same settings, without having to remount

### ISSUE THREAD

**Issue by InternalLoss** [emukidid/cleanrip#58]
A lot of people dump their Wii games en masse for submission to Redump, and it has been noted that a streamline way to continue dumping a new disc would be preferred. Currently, the flow is:

Pick Destination -> Pick FileSystem -> Initialise Destination -> Initialise Disc -> Select Settings -> dump.

However, after a dump has completed, this is yet again ran through (albeit with the settings being the same per-session). It would be a much better help if the settings were able to be set permanently (i.e. a config file on SD), with perhaps a simple "dump another disc" button that initialises disc and dumps again to the last place with same settings.

**Comment by emukidid** [comment]
[2.1.1](https://github.com/emukidid/cleanrip/releases/tag/2.1.1) now has the ability to keep your settings for the duration of a ripping session, please give it a shot.
