### ISSUE TITLE
Verification

### ISSUE THREAD

**Issue by 1superchip** [emukidid/cleanrip#68]
Hello, I have an issue with the wii.dat file. I am wondering where to put it in my sd card. I cannot download it since my wii is not connected to wifi.

**Comment by Bombastisch** [comment]
You have to put it into the root directory of your SD card to work

**Comment by Fastigium** [comment]
More precisely, you have to put them in the root directory of the storage device you're planning to rip to. If that happens to be your SD card, then put them there, but in my case, they had to be in the root directory of the USB stick I wanted to rip to :slightly_smiling_face:

**Comment by Bombastisch** [comment]
The code should probably be changed to just check both devices. That would make it a lot easier.
And maybe put the .dat files into the CleanRip folder instead of the root directory.
