### ISSUE TITLE
Dat Files not detected

### ISSUE THREAD

**Issue by RomainL972** [emukidid/cleanrip#71]
Hi, when I first started CleanRip on my Wii, it downloaded the wii.dat and gc.dat files on my usb drive. However, the second time it said that the files weren't found. When I choose to re-download, I get a black screen and the console crashes. When I choose not to download, it freezes. The only solution I found is to delete the files with my computer then re-download each time I start CleanRip.

**Comment by majorpbx** [comment]
I too have this problem. Only deleting the dat files to let Cleanrip re-download works.

**Comment by emukidid** [comment]
Some recent changes may have resolved this. Closing.
