### ISSUE TITLE
Can't rip Sims 2 PAL

### ISSUE THREAD

**Issue by tadeldelelolilul** [emukidid/cleanrip#72]
Hello, as you can read in the subject, I've problem with rip that game. Other games like Mario Kart Double Dash PAL without any problems. Rip Datel disc no problem too. I've tried rip with USBLoader GX too, same here. I don't know what to do. Maybe it can be fixed. Weird thing is, that it is normally playable on both Gamecube and Wii... Seems no problem with the disc ... P.S. I tried rip on Wii only.

**Comment by emukidid** [comment]
Seems like the disc is bad. There's nothing custom per game that is done in CleanRip so if it can't rip it's because it can't be read successfully.
