### ISSUE TITLE
Black Screen of Death on first installation

### ISSUE THREAD

**Issue by edwinbradford** [emukidid/cleanrip#79]
It's difficult for me to explain how to reproduce this because I'm working from memory but to the best of my ability these are the steps that caused the issue.

1. Download CleanRip-v2.1.1.zip, gc.dat and wii.dat
2. Extract CleanRip-v2.1.1 and place it in the Apps folder on the USB.
3. Place gc.dat and wii.dat in the root of the USB.
4. Launch CleanRip from the Homebrew channel.
5. At the screen that asks if you want to download / update (?) the database select yes.
6. After a while the system crashes with the Black Screen of Death shown.

I rebooted the Wii, everything seems to be fine and I subsequently ripped a game disc with no apparent problems. I already had gc.dat and wii.dat which I believe contain the games database but opted to update or download the database over Wi-Fi.

Hopefully the attached image will help you debug the issue. 

[image.png](https://postimg.cc/v1MRTsLt)

**Comment by Pokechu22** [comment]
This crash (or a similar one; I haven't compared the crash screen) seems to happen immediately after updating the database, specifically after it finishes downloading the Wii one.  I think it successfully downloads the updated version, and then immediately crashes before prompting for disc configuration, but I'm not 100% sure (I haven't checked whether it actually successfully updated, and I'm not sure if it crashes 100% of the time).

**Comment by bibarub** [comment]
fixed in https://github.com/emukidid/cleanrip/pull/114
