### ISSUE TITLE
Are faster Wii dumps possible?

### ISSUE THREAD

**Issue by schicho** [emukidid/cleanrip#82]
Wii dumps take around 22 minutes (give or take depending on if checksum calculation is enabled).
The average dumping speed is around 3.15 MB/s. This is the maximum read speed of the Gamecube Discs.

Wii Discs on the other hand support 6x DVD read speed, which equals around 8.11 MB/s.
[This thread on GBATemps](https://gbatemp.net/threads/actual-read-speed-of-the-wiis-dvd-drive.370972/) also addresses this question, but it's claimed in the second answer that softmod is limited to 3x speeds.

This limitation seems rather unrealistic, why should faster speeds not be possible? It would half the dumping speed to 11 minutes, which is completely possible with USB 2.0 speeds.

Have you looked into this before? Would it require some extra functions not provided with DevkitPro? And if so how hard would it be to implement? Surely some other homebrew utilities must have tried this before?

**Comment by emukidid** [comment]
I remember back when I was using a hardmod on my DVD drive and developing CleanRip I'd put a .hex variant that locked the drive to 6x mode for all media (bad idea in hindsight), with that I was getting super fast rips for both GC/Wii. I believe the disc speed can be controlled, but it should default to 6x on Wii media by default anyway. I'll look into this more and see if I can  query the drive to return the current speed.

**Comment by schicho** [comment]
Interesting! I only have a PAL Wii, so unless the US/JP variants behave differently, I only ever have had the "slow" 3x dumping speed.

Interesting to hear tho that 6x speed should be possible without further code changes, but having the disc speed increased.

It sounds like a problem that can be tackled!

**Comment by schicho** [comment]
After looking into the problem again, I noticed this was my mistake... I forgot that the disk speed changes depending on position on the disk. So the disk speed is already at maximum afaik. Attempts to set the disk speed https://wiibrew.org/wiki//dev/di#0xDD_DVDLowSetMaximumRotation failed for me.

**Comment by emukidid** [comment]
It should be noted for posterity that those old drive chips did indeed make GameCube discs run at Wii disc speeds, but via software this isn't possible.
