### ISSUE TITLE
Can't mount disk

### ISSUE THREAD

**Issue by omerien** [emukidid/cleanrip#83]
What steps will reproduce the problem?
1. I downloaded CleanRip v2.0.0
2. Everything is formatted, so I load the program
3. Says to Insert a USB FAT 32/NTFS formatted device (which I do), then gives 
me the error message.

What is the expected output? What do you see instead?
To begin ripping wii disc.  The error mounting device message

What version of the product are you using? On what operating system?
v2.1.1 on Wii 4.3E

Please provide any additional information below.
I can't seem to find anything I am doing differently from everyone else.  
Please help.

**Comment by emukidid** [comment]
Try again on a later release.
