### ISSUE TITLE
NTFS or other filesystem on gamecube

### ISSUE THREAD

**Issue by bebewold** [emukidid/cleanrip#84]
Would it be possible to add NTFS or exFat support on gamecube? Fat32 is a bit slow when I'm trying to transfer files, I'd like to be able to use a faster filesystem with my Gamecube

**Comment by bebewold** [comment]
I'm asking because it says nfts is supported but it only seems to work on a wii

**Comment by 5p4rkP1ug** [comment]
Can also confirm that I'm facing a similar issue on GameCube. Limited to FAT32 formatted volumes well and truly sucks.

**Comment by emukidid** [comment]
NTFS has been added.
