### ISSUE TITLE
Feature request: eject disc from Wii after ripping

### ISSUE THREAD

**Issue by williamtheaker** [emukidid/cleanrip#89]
Pressing A at this screen should eject the disc inside the Wii
```
X disc(s) dumped
Dump another disc?
Press A to continue 
```

I don't know if it's possible to have the inserted disc start dumping without hitting A, but it would speed up the process if it did.

**Comment by emukidid** [comment]
Eject should happen now. If you still want to see it auto-start on insert, split this one off into a separate ticket and I'll have a look one day.
