### ISSUE TITLE
Exseption (DSI) Occurred!

### ISSUE THREAD

**Issue by Baron272** [emukidid/cleanrip#90]
Having an issue when installing cleanrip through the Homebrew channel, tried multiple times same error code, spent an hour or so looking for any forum post or comment about this specific error, couldn't find any. Any help would be vastly appreciated. (Also had to write that out by hand, so I hope I didn't make any mistakes)

Exseption (DSI) occurred!
GPR00 00000028 GPR08 00000000 GPR16 00000000 GPR24 00000000
GPR01 802C63A8 GPR09 00000001 GPR10 00000000 GPR25 00000000
GPR02 801D4940 GPR10 803A4EC8 GPR18 00000000 GPR26 0000000E
GPR03 00000001 GPR11 803CA5FC GPR19 00000000 GPR27 00000000
GPR04 803A4E58 GPR12 803CA5FC GPR20 00000000 GPR28 00000000
GPR05 00000000 GPR13 801E9060 GPR21 00000000 GPR29 00000000
GPR06 000DA82C GPR14 00000000 GPR22 00000000 GPR30 803A4E58
GPR07 000DA854 GPR15 00000000 GPR23 00000000 GPR31 00000029
LR 800571D8 SRR0 80049628 SRR1 00001032 MSR 00001000
DAR 0000000C DSISR 06000000

STACK DUMP: 
80049628 --> 800571d8 --> 8005ac84 --> 80009bc8 -->
800062d4 --> 80047af8 --> 80047a5c

CODE DUMP:
80049628:  9148000C 810B0008 910A0008 48000070
80049638:  810B0004  71070001 40820044 7C080214
80049648:  5408003C 900A0004 7C0A412E 810B0008

**Comment by emukidid** [comment]
Can you post a video by any chance?

**Comment by Baron272** [comment]
> Can you post a video by any chance?

I can, I will try to get it recorded tomorrow, that is if it is still not functioning.

**Comment by Starfoxfs** [comment]
I having the same Problem with Version 2.1.2

If i choose dump to NTFS with Checksums.

If i choose FAT32 it works fine.

My Drive is a WD Scorpio Blue 320GB 2 Partitions 1x 80GB FAT32 and 1x 240GB NTFS connected with a UGREEN USB 3.2 HDD Case 2,5 Zoll

https://www.amazon.com/UGREEN-Festplattengeh%C3%A4use-Geh%C3%A4use-unterst%C3%BCtzt-werkzeugfreie/dp/B07D2BHVBD

![2024-01-20-15-24-15-645](https://github.com/emukidid/cleanrip/assets/62878094/6c3f1faa-f4c5-4330-8cbd-2291f2d5650a)

**Comment by emukidid** [comment]
NTFS is somewhat broken, try the latest build from the CI, or wait for the next release.
