### ISSUE TITLE
Unrecovered Read Error

### ISSUE THREAD

**Issue by Prysmarine** [emukidid/cleanrip#94]
I'm having issues getting Fire Emblem Path of Radiance (GC) and Fire Emblem Radiant Dawn (Wii) to rip, both give an Unrecovered Read Error, PoR at ~2%, RD at ~25%. The discs have less scratches than most other games I ripped, and are still readable and playable by the console. Is there anything I can try short of attempting a resurfacing?

**Comment by emukidid** [comment]
There isn't really anything CleanRip can do at this current time sorry.
